# Generated by Django 2.0 on 2020-08-23 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('usuario', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('fechanacimiento', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='tipodocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='tipodocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.tipodocumento'),
        ),
    ]
